apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.productService.port }}
