apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - microservices-gateway
  http:
  - route:
    - destination:
        host: frontend
        port:
          number: 80
      weight: 100
